name: pantry_organiser_frontend
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  device_preview: ^1.2.0
  http: ^1.2.1
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5
  reactive_forms: ^17.0.1
  reactive_date_time_picker: ^3.0.1
  go_router: ^14.2.1
  freezed_annotation: ^2.4.3
  gap: ^3.0.1
  date_format: ^2.0.7
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  generate: true
