name: pantry_organiser_frontend
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  fluttertoast: ^8.2.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.4
  device_preview: ^1.2.0
  http: ^1.3.0
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  reactive_forms: ^17.0.1
  reactive_date_time_picker: ^4.0.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  google_fonts: ^6.2.1
  date_format: ^2.0.9
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  http_interceptor: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  riverpod_lint: ^2.6.4
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  generate: true
